server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8080
              predicates:
                - Path=/auth/**

            - id: task-service
              uri: http://task-service:8080
              predicates:
                - Path=/tasks/**
jwt:
  secret: UniversalFavoriteAndSuperHandsomeSongjoongkiSecretKey12345
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,gateway